package webdriver;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;
public class AssertionTest1 {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void assertion() throws InterruptedException {
    driver.get("https://www.facebook.com/");
    driver.manage().window().setSize(new Dimension(674, 800));
    driver.findElement(By.id("email")).sendKeys("7729024404");
    driver.findElement(By.id("pass")).sendKeys("@Praveen1");
    Thread.sleep(4000);
    driver.findElement(By.linkText("Create New Account")).click();
    Thread.sleep(4000);
    driver.findElement(By.name("firstname")).click();
    driver.findElement(By.name("firstname")).sendKeys("praveen");
    {
     
    }
    driver.findElement(By.name("firstname")).click();
    {
     
    } Thread.sleep(4000);
    {
      WebElement element = driver.findElement(By.id("day"+Keys.ARROW_UP));
      Thread.sleep(4000);
      Boolean isEditable = element.isEnabled() && element.getAttribute("readonly") == null;
      assertTrue(isEditable);
      
    }
    driver.findElement(By.xpath("//span[2]/input")).click();
    assertTrue(driver.findElement(By.xpath("//span[2]/input")).isSelected());
    assertThat(driver.findElement(By.name("websubmit")).getText(), is("Sign Up"));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".\\_52lq"));
      assert(elements.size() > 0);
    }
  }
}
